"vec4 encode(float val)\n"
"{\n"
"    return vec4(mod(val * 65536, 1.0), mod(val * 256, 1.0), mod(val, 1.0), 0.0);\n"
"}\n"
"\n"
"float decode(vec4 val)\n"
"{\n"
"    return dot(val.xyz, vec3(1, 1/256.0, 1/65536.0));\n"
"}\n"
"\n"
"vec4 paraboloid(vec4 val)\n"
"{\n"
"    val /= val.w;\n"
"    float L = length(val.xyz);\n"
"    val /= L;\n"
"    float zval = val.z + 1;\n"
"    return vec4(val.xy / zval, val.z, L);\n"
"}\n"
"\n"
